/**
 * SECURITY
 */
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGOUT = 'LOGOUT';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

/**
 * NAVIGATION
 */
export const NAVIGATE_TO_CART = 'NAVIGATE_TO_CART';
export const NAVIGATE_TO_LOGIN = 'NAVIGATE_TO_LOGIN';
export const NAVIGATE_TO_REGISTER = 'NAVIGATE_TO_REGISTER';

/**
 * USER
 */
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER = 'FETCH_USER';
export const GET_USER_DELIVERY_ADDRESSES = 'GET_USER_DELIVERY_ADDRESSES';

/**
 * PLACE
 */
export const GEOCODE_SUCCEEDED = 'GEOCODE_SUCCEEDED';
export const ADD_USER_PLACE = 'ADD_USER_PLACE';

/**
 * ORDER
 */
export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';
export const SET_ORDER_DELIVERY_ADDRESS = 'SET_ORDER_DELIVERY_ADDRESS';
export const SET_ORDER_CART = 'SET_ORDER_CART';
export const SET_ORDER_SERVICE = 'SET_ORDER_SERVICE';
export const REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM';
