/**
 * SECURITY
 */
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGOUT = 'LOGOUT';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

/**
 * NAVIGATION
 */
export const NAVIGATE_TO_LOGIN = 'NAVIGATE_TO_LOGIN';
export const NAVIGATE_TO_REGISTER = 'NAVIGATE_TO_REGISTER';

/**
 * USER
 */
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_PLACES = 'FETCH_USER_PLACES';

/**
 * PLACE
 */
export const GEOCODE_SUCCEEDED = 'GEOCODE_SUCCEEDED';
export const ADD_USER_PLACE = 'ADD_USER_PLACE';

/**
 * ORDER
 */
export const ORDER_PLACE_SET = 'ORDER_PLACE_SET';